Added Os.ark and home_dir function
ArkScript-lang/std pull request #9
Opened 2020-12-11 18:50 UTC by Wafelack

- Added a home_dir function (not cross platform at all for now) displaying current user home dir

2020-12-12 20:00 UTC, SuperFola commented on Os.ark
> +# @meta Os
rename to `os`

2020-12-12 20:01 UTC, SuperFola commented on Os.ark
> +  (mut res "")
remove, it isn't used

2020-12-12 20:01 UTC, SuperFola commented on Os.ark
> +# @meta Os
rename to OS or os according to the new filename

2020-12-12 20:02 UTC, SuperFola commented on Os.ark
> +    ( + "/home/" whoami))
removing useless white space between `(` and `+`

2020-12-12 20:02 UTC, SuperFola requested changes
either rename to OS.ark or os.ark, Os.ark is weird because it's Operating System and both words are important

2020-12-12 21:05 UTC, Wafelack commented on Os.ark
> +  (mut res "")
What to remove ? The whole 4 lines ?

2020-12-12 21:08 UTC, Wafelack commented on Os.ark
> +  (mut res "")
Ok no i finally understood

2020-12-13 11:36 UTC, SuperFola approved these changes

2020-12-13 11:38 UTC, merged

2020-12-13 11:38 UTC, SuperFola commented
TODO for later
- add on the README.md
- update later when we'll have a better way to retrieve the output of a sys call
- make it work on linux and windows